#https://github.com/prometheus/alertmanager/blob/master/doc/examples/simple.yml
route:
  receiver: "slack"

receivers:
  - name: "slack"
    slack_configs:
      - send_resolved: true
        text: "{{ .CommonAnnotations.description }}"
        username: "Prometheus"
        channel: "#<Prometheus-Alerts>"
        api_url: "https://hooks.slack.com/services/<webhook-id>"
        #to insert as channel is created
